/**
 * Internal helpers for admin server actions.
 *
 * Functions in this file are NOT server actions themselves — they are pure
 * utilities consumed by sibling files (`donation-files.ts` etc.). The leading
 * underscore signals this; do not export these from the barrel `index.ts`.
 */

import sharp from 'sharp'

import { logger } from '@/lib/logger'
import type { getAdminClient } from '@/lib/supabase/action-clients'

type SupabaseClient = Awaited<ReturnType<typeof getAdminClient>>

interface ThumbnailOptions {
  supabase: SupabaseClient
  /** Buffer of the source image; thumbnail is generated by `sharp` from this. */
  sourceBuffer: Buffer
  donationPublicId: string
  /** Timestamp portion of the original filename, used as the thumbnail filename prefix. */
  timestamp: string
  /** Whether to allow overwriting an existing thumbnail at the same path. */
  upsert?: boolean
}

/**
 * Generate a 300px-wide JPEG thumbnail of `sourceBuffer` and upload it to
 * `donation-results/{donationPublicId}/.thumbnails/{timestamp}_thumb.jpg`.
 *
 * Failures are logged but never thrown — thumbnail is best-effort.
 */
export async function generateAndUploadThumbnail({
  supabase,
  sourceBuffer,
  donationPublicId,
  timestamp,
  upsert = false,
}: ThumbnailOptions): Promise<void> {
  try {
    const thumbnailBuffer = await sharp(sourceBuffer)
      .resize(300, null, { withoutEnlargement: true, fit: 'inside' })
      .jpeg({ quality: 80 })
      .toBuffer()

    const thumbnailFileName = `${timestamp}_thumb.jpg`
    const thumbnailPath = `${donationPublicId}/.thumbnails/${thumbnailFileName}`

    await supabase.storage.from('donation-results').upload(thumbnailPath, thumbnailBuffer, {
      contentType: 'image/jpeg',
      cacheControl: '3600',
      upsert,
    })

    logger.debug('ADMIN', 'Thumbnail created', { fileName: thumbnailFileName })
  } catch (thumbnailError) {
    logger.error('ADMIN', 'Failed to generate thumbnail', {
      error: thumbnailError instanceof Error ? thumbnailError.message : String(thumbnailError),
    })
  }
}
